Repository acm-ucr/hackathon_discord_bot, pull requests merged in 2023-07, with the labels that each got.

#2 role working
  .github/workflows/pull_request.yaml
  bot/main.py
Labels: ready to review

#4 move to different file
  bot/main.py
  bot/roles.py
Labels: ready to review

#9 Cleanup + Typing
  bot/main.py
  bot/roles.py
Labels: Ready to Review, Roles

#13 Add Volunteer + Mentor Requesting
  bot/main.py
  bot/roles.py
Labels: Ready to Review, Roles

#3 Echo Events from google calender
  .pylintrc
  bot/main.py
  bot/scheduler.py
  pyproject.toml
Labels: Do Not Merge, Events

#16 Typing Fixes
  bot/main.py
  bot/mentor.py
  bot/roles.py
  bot/scheduler.py
Labels: Ready to Review, Bug Fix

#17 private
  bot/mentor.py
Labels: Ready to Review

#18 Add Welcome Message
  bot/main.py
  bot/mentor.py
  bot/roles.py
  bot/scheduler.py
  bot/welcome.py
Labels: Ready to Review, Welcome

#19 Update README.md
  .github/workflows/pull_request.yaml
  .gitignore
  README.md
  bot/mentor.py
  pyproject.toml
  tests/__init__.py
Labels: Ready to Review, Repository
